---
# This Playbook operates experiment environments on on Amazon EC2
# Init this playbook with appropriate tags
# - monitoring_started
# - monitoring_stoped

- hosts: tag_cassandra_true:tag_kairos_true:tag_newts_true:tag_ycsb_true
  remote_user: ubuntu
  gather_facts: yes
  vars_files:
  # Importing OS related variables, e.g., "group_vars/ubuntu".
  - "group_vars/{{ ansible_distribution }}"
  # Importing cloud provider related variables, e.g., "group_vars/aws".
  - "group_vars/aws"
  - "roles/dstat/vars/main.yml"
  tasks:
  - include: roles/dstat/tasks/enabled_monitoring.yml