---
# file: /roles/newts/tasks/main.yml

- name: Create temporary dir 'tmp' on remote node
  file: >
    path={{ tmp_dir }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Download tar ball from S3
  get_url: >
    url={{ newts_uri }}
    dest={{ tmp_dir }}

- name: Untar tar ball
  command: tar -xvf {{ tmp_dir }}/{{ newts_tar_name }} -C {{ tmp_dir }}

  # touch untared dir, but add/remove some permissions
- file: >
    path={{ tmp_dir }}/{{ newts_untar_name }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Remove install dir
  sudo: yes
  file: > 
    path={{ newts_install_dir }}
    state=absent

- name: Create target dir on remote node
  sudo: yes
  file: >
    path={{ newts_home }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Copy content of extracted tar ball to install dir
  sudo: yes
  shell: "mv {{ tmp_dir }}/{{ newts_untar_name }}/* {{ newts_home }}/"

- name: Remove conf file '$NEWTS_HOME/etc/config.yaml'
  sudo: yes
  file: > 
    path={{ newts_home }}/etc/config.yaml
    state=absent

- name: Create conf file '$NEWTS_HOME/etc/config.yaml'
  template: >
    src=config.yaml.j2
    dest={{ newts_home }}/etc/config.yaml
    owner={{ user }}
    group={{ user }}
    mode=0755

- name: Remove tmp dir
  sudo: yes
  file: > 
    path={{ tmp_dir }}
    state=absent
